---
- name: "Create containerd modules configuration file"
  ansible.builtin.copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
    mode: '0644'

- name: "Load kernel modules for Containerd"
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: "Enable IPv4 forwarding for Kubernetes networking"
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    state: present
    reload: yes

- name: "Enable Bridge Netfilter (iptables)"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    state: present
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: "Install containerd via apt"
  ansible.builtin.apt:
    name: containerd
    state: present
    update_cache: yes

- name: "Deploy containerd configuration"
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  notify: Restart containerd 

- name: "Ensure containerd is running and enabled at boot"
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: yes
