---
- name: "Ensure keyrings directory exists"
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: "Download Kubernetes public signing key"
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key
    dest: /tmp/kubernetes-release.key
    mode: '0644'

- name: "Dearmor Kubernetes key"
  ansible.builtin.command:
    cmd: gpg --dearmor --yes -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: "Add Kubernetes apt repository"
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /"
    filename: kubernetes
    state: present

- name: "Install Kubernetes binaries"
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: "Prevent Kubernetes packages from being automatically updated"
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl